### ISSUE TITLE
Fix docstrings in sliders.spatial

### ISSUE THREAD

**Issue by bolliger32** [ClimateImpactLab/sliiders-archived#13]
At least this one seems to be incorrect - corresponding to a different function: https://github.com/ClimateImpactLab/sliiders/blob/4ce8f445c0223f5aad2680c876af4a6fdef05ddc/sliiders/spatial.py#L111

**Comment by jtschoi** [comment]
The above issue has been resolved (as of merging PR #20), but there are some that still require docstrings. They are:
- [ ] `get_reg_group`
- [ ] `fix_ring_topology`

I will add the docstrings to these and make a separate PR.
