### ISSUE TITLE
Merge data acquisition notebooks

### ISSUE THREAD

**Issue by bolliger32** [ClimateImpactLab/sliiders-archived#16]
It would be helpful to have data acquisition in one notebook. Right now we have:

- [create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb](../tree/main/notebooks/create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb)
- [create-SLIIDERS-ECON/exposure/data_acquisition/download-srtm-plus.ipynb](../tree/main/notebooks/create-SLIIDERS-ECON/exposure/data_acquisition/download-srtm-plus.ipynb)
- [create-SLIIDERS-ECON/country_level_ypk/ypk1_data_acquisition.ipynb](../tree/main/notebooks/create-SLIIDERS-ECON/country_level_ypk/ypk1_data_acquisition.ipynb)

Can we merge those latter two into the first one?

**Comment by jtschoi** [comment]
Issue resolved with the following PR: https://github.com/ClimateImpactLab/sliiders/pull/18
